---
site_name: LTRCCT-2296 From Good to Great - Enhancing Customer Experience with the Webex Contact Center Flow Designer
site_description: LTRCCT-2296 From Good to Great - Enhancing Customer Experience with the Webex Contact Center Flow Designer
site_author: Kevin Simpson, Chandramouli Vaithiyanathan
# must be same as "site_name"
copyright: Copyright &copy; 2025 Cisco Systems Inc. All Rights Reserved.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
    - content.tooltips
    - content.footnote.tooltips
    - codehilite
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom      
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/cisco_logo.png
  favicon: template_assets/cisco_logo.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/copy-button.js
  - js/attendee-id.js
  - template_assets/newLoad.js
plugins:
  - search
  # - with-pdf:
  #     cover_title: LTRCCT-2296
  #     cover_subtitle: "From Good to Great: Enhancing Customer Experience with the Webex Contact Center Flow Designer"
  #     cover_logo: template_assets/Cisco-Live-White-Blue-APJC.svg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top   
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  # - Test1234: test1234.md
  - Getting Started:
    - Welcome: postEvent.md
    - Overview: peOverview.md
    # - Welcome: welcome.md
    # - Overview: overview.md
  - Core:
      - Lab 1: coreLab1.md
      - Lab 2: coreLab2.md
      - Lab 3: coreLab3.md
      - Lab 4: coreLab4.md
      - Lab 5: coreLab5.md
      - Understanding JSON: json.md
  - Adventure Section: adventureList.md
  - Cheat Sheet: cheatsheet.md
  # - Login Info: creds.md
  # - Ask a Question<i class="fa-solid fa-hand" style="color:#63E6BE;"></i>: slido-QA-iFrame.md

